# Generated by Django 6.0.4 on 2026-05-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("author", models.CharField(max_length=150, verbose_name="Автор")),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        default="Не указан", max_length=100, verbose_name="Жанр"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступна"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
            ],
        ),
    ]
