# Generated by Django 6.0.4 on 2026-05-20 18:39

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_book_tags_alter_book_slug"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL-адрес"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Место проведения"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Теги",
            ),
        ),
    ]
