# Generated by Django 6.0.4 on 2026-05-31 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_event_book_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subgenres",
                to="catalog.genre",
                verbose_name="Родительский жанр",
            ),
        ),
    ]
